# Generated by Django 5.0.3 on 2024-03-31 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Модель ведущего моста', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Модель ведущих мостов',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Модель двигателя', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Модель двигателей',
            },
        ),
        migrations.CreateModel(
            name='FailureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Узел отказа', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Узлы отказа',
            },
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Модель техники', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
                'verbose_name_plural': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Вид ТО', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.CreateModel(
            name='RepairProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Способ восстановления', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'Способы восстановления',
            },
        ),
        migrations.CreateModel(
            name='ServiceDepInOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Организация, проводившая ТО', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Организация, проводившая ТО',
                'verbose_name_plural': 'Организации, проводившие ТО',
            },
        ),
        migrations.CreateModel(
            name='SteerAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Модель управляемого моста', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Модель управляемых мостов',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Модель трансмиссии', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Модель трансмиссий',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Клиент', max_length=255, verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ServiceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Сервисная компания', max_length=255, verbose_name='Описание')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=255, unique=True, verbose_name='Заводской № машины')),
                ('engine_number', models.CharField(max_length=255, unique=True, verbose_name='Заводской № двигателя')),
                ('transmission_number', models.CharField(max_length=255, unique=True, verbose_name='Заводской № трансмиссии')),
                ('drive_axle_number', models.CharField(max_length=255, verbose_name='Заводской № ведущего моста')),
                ('steer_axle_number', models.CharField(max_length=255, verbose_name='Заводской № управляемого моста')),
                ('delivery_contract', models.CharField(max_length=255, verbose_name='Договор поставки (№, дата)')),
                ('shipment_date', models.DateField(max_length=50, verbose_name='Дата отгрузки с завода')),
                ('end_user', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('configuration', models.TextField(default='Стандарт', max_length=1000, verbose_name='Комплектация (доп. опции)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.client', verbose_name='Покупатель')),
                ('drive_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.driveaxle', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_engine', to='silant_servibook.engine', verbose_name='Модель двигателя')),
                ('service_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.servicedepartment', verbose_name='Сервисная компания')),
                ('steer_axle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.steeraxle', verbose_name='Модель управляемого моста')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.transmission', verbose_name='Модель трансмиссии')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_machinery', to='silant_servibook.machinery', verbose_name='Модель техники')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(max_length=1000, verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(blank=True, max_length=1000, verbose_name='Используемые запасные части')),
                ('repair_date', models.DateField(max_length=50, verbose_name='Дата восстановления')),
                ('nonuse_time', models.IntegerField(default=0, verbose_name='Время простоя техники')),
                ('failure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.failureunit', verbose_name='Узел отказа')),
                ('repair_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.repairprocedure', verbose_name='Способ восстановления')),
                ('service_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.servicedepartment', verbose_name='Сервисная компания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(max_length=50, verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(default=0, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=255, verbose_name='Номер заказ-наряда')),
                ('order_date', models.DateField(max_length=50, verbose_name='Дата заказ-наряда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.maintenancetype', verbose_name='Вид ТО')),
                ('service_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.servicedepartment', verbose_name='Сервисная компания')),
                ('maintenance_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.servicedepinoperation', verbose_name='Организация, проводившая ТО')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_servibook.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
        ),
    ]
